### ISSUE TITLE
Upgrade to lifelines 0.7.0.0

### ISSUE THREAD

**Issue by CamDavidsonPilon** [agartland/TB_SnT#1]
Hey @agartland, there was a bug in the `logrank_test` in lifelines. You can see this discussion [here](https://github.com/CamDavidsonPilon/lifelines/pull/135#discussion_r25569695). It's recommended you upgrade to the latest lifelines with 

`pip install --upgrade --no-deps lifelines` 

to get version 0.7.0.0. Thanks!

**Comment by agartland** [comment]
Thanks @CamDavidsonPilon. I'm caught up now. Hopefully when I finish this project I'll have something to contribute back to lifelines. Specifically I'm doing work with hazard ratios and cumulative hazard ratios that may be of general interest and would be easy to add-on.

**Comment by CamDavidsonPilon** [comment]
Great! Looking forward to see your completed work!
